# Change these first
owner: bothyculture # Your GitHub organization or username, where this repository lives
repo: world-bike-map-upptime # The name of this repository

sites:
  - name: worldbikemap.com
    url: https://worldbikemap.com
  - name: opencyclemap
    url: https://a.tile.thunderforest.com/cycle/17/64402/40844@2x.png?apikey=49f65477e83d4c988d1cc6bb104ab64d

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.worldbikemap.com
  # baseUrl: /your-repo-name
  logoUrl: https://worldbikemap.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.9f3e81c8.png&w=3840&q=75
  name: World Bike Map - Status Page
  introTitle: "System Status"
  introMessage: This is the status page for worldbikemap.com and the mobile apps
  navbar:
    - title: Home
      href: https://worldbikemap.com
    - title: Status
      href: /
  themeUrl: https://worldbikemap.com/theme.css
  favicon: https://worldbikemap.com/favicon.ico
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
